FROM node:16-bullseye-slim AS builder

WORKDIR /build
COPY ruoyi-ui/package*.json ./
RUN npm install --legacy-peer-deps
COPY ruoyi-ui/ ./
ENV NODE_OPTIONS=--max-old-space-size=1024
RUN npm run build:prod

FROM nginx:1.26.3-alpine
COPY deploy/nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=builder /build/dist/ /usr/share/nginx/html/

EXPOSE 80
